In [4]:
my_list = [1,2,3,4,5,6,7,8,9,10]
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
import numpy as np
print(np.array(my_list))

my_arr = np.array(my_list)
print(my_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
my_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
print(my_matrix[0],my_matrix[1],my_matrix[2])
print(np.array(my_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3] [4, 5, 6] [7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
########usage of np.arange() function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5) ###creating a numpy array of 5 floats all of which are set to 0.0

array([0., 0., 0., 0., 0.])

In [13]:
print(np.zeros(10)) ###creating a numpy array of 10 floats all of which are set to 0.0, and printing this array

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
np.random.rand(7)

array([0.70006109, 0.22565199, 0.82281409, 0.80582257, 0.23276423,
       0.0411086 , 0.61993594])

In [15]:
np.random.randn(10)

array([ 1.33612222,  0.39319727,  0.27202893, -0.03735398, -0.308854  ,
       -0.1393909 ,  0.34423817,  0.63296085,  0.69958305,  0.64449863])

In [16]:
np.random.rand(7,7) ##generates a 7 by 7 matrix where each element is drawn from a uniform distribution over [0,1).

array([[0.37881319, 0.65714715, 0.66569783, 0.24016758, 0.66629356,
        0.85759724, 0.19110124],
       [0.31453347, 0.54583564, 0.83946188, 0.23364999, 0.98894656,
        0.07193728, 0.0199964 ],
       [0.36053213, 0.9978004 , 0.39773124, 0.33997314, 0.1397598 ,
        0.5344856 , 0.21286556],
       [0.65806756, 0.5082521 , 0.30086   , 0.29659035, 0.11812834,
        0.12085911, 0.58355236],
       [0.86817958, 0.29795581, 0.70557564, 0.35078802, 0.30965996,
        0.75854231, 0.34308685],
       [0.15139574, 0.14513453, 0.62230136, 0.53111778, 0.86291189,
        0.70092068, 0.7764045 ],
       [0.08053443, 0.29485972, 0.55535117, 0.58955235, 0.7548479 ,
        0.57103867, 0.60512233]])

In [17]:
print(np.random.randn(11,11)) ##generates a 11 by 11 matrix where each element is drawn from a standard normal distribution.

[[-1.65918387 -1.90501228  0.32661489  0.47216933 -2.11892459 -1.4651663
  -1.03399711  0.0347166   0.50419294  1.36051078  0.39948438]
 [-0.23549583  0.52460858 -0.34689986  0.86311944 -1.94996063 -0.51780786
  -0.54141562  1.34548953 -0.12629124  0.46265045 -2.01701126]
 [ 0.32479176 -0.36773602 -2.27754532  0.36825691 -1.12823102 -1.41721003
  -0.04842744 -0.45866876  0.99471887  1.03489605  0.51426405]
 [-1.21179941 -1.07225227 -2.11254967  0.52762136  0.75175067 -0.65203682
  -0.72977538 -0.4681337  -0.78697056  0.65276496 -0.53632842]
 [-2.05900615  0.54357707 -1.40799563 -1.41348048 -0.72712878 -1.29645695
  -0.89519018  0.13660922 -0.23348747  0.17163489  1.55609212]
 [-1.08351347 -2.58029792  0.06372445  0.93980511 -0.75242972 -0.54041509
   1.24284714  1.08514128  0.0535021  -0.26341547  0.42301117]
 [ 0.49160196  1.08926558  0.52294828  0.55634053 -1.2048919  -0.8354908
   0.22267682  0.18871493  1.74959306  0.04145153  0.03643855]
 [-0.0073976   1.89595432  0.10915329  0.03

In [18]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [19]:
print(np.random.randint(1, 100, 10)) ####gets 10 random integers from the range starting at 1 and ending at 99.

[59 99 46  9 27 14 96 16 73 97]


In [20]:
arr = np.arange(0, 100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [21]:
##########Reshape method of Numpy
arr.reshape(10,10) #####reshaping the array into 10 by 10 array.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
rand_arr = np.random.randint(1, 100, 10)
rand_arr.min()

8

In [23]:
rand_arr.max()

98

In [24]:
print(rand_arr.argmax()) ###gets the index of the maximum element
print(rand_arr.argmin()) ###gets the index of the minimum element

8
6


In [25]:
##########usage of shape() function to determine the number of rows and columns in an array
arr.shape

(100,)

In [26]:
rand_arr.shape

(10,)

In [27]:
arr.shape[0]

100

In [28]:
rand_arr.shape[0]

10

In [29]:
from numpy.random import randint
randint(2,10)

7

In [30]:
###Numpy Indexing and Selection
import numpy as np

In [31]:
my_array = np.arange(0,11)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [32]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
print("First element of the my_array: "+str(my_array[0])+"")
print("Second element of the my_array: "+str(my_array[1])+"")
print("Third element of the my_array: "+str(my_array[2])+"")

print(my_array[3:9]) ###get the elements starting at index 3 and ending at index 8 (index 9 is exclusive)

First element of the my_array: 0
Second element of the my_array: 1
Third element of the my_array: 2
[3 4 5 6 7 8]


In [34]:
slice_of_arr = my_array[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [35]:
slice_of_arr[:] = 99

In [36]:
print(slice_of_arr)
print(my_array)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [37]:
#######usage of copy() method
copy_arr = my_array.copy()

copy_arr[:] = 111 ###make all elements in the copy array 111
print(copy_arr) 
print(my_array)

[111 111 111 111 111 111 111 111 111 111 111]
[99 99 99 99 99 99  6  7  8  9 10]


In [38]:
#####Indexiing a 2D Numpy Array

array_2d = np.array([[10,15,20],[25,30,35],[40,45,50]])

In [39]:
array_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [40]:
###Double Bracket Format to reach elements in a 2D Numpy array
array_2d[0][1]

15

In [41]:
print(array_2d[0][0])  ##10
print(array_2d[0][1])  ##15
print(array_2d[0][2])  ##20

print()

print(array_2d[1][0])  ##25
print(array_2d[1][1])  ##30
print(array_2d[1][2])  ##35

print()

print(array_2d[2][0])  ##40
print(array_2d[2][1])  ##45
print(array_2d[2][2])  ##50

SyntaxError: invalid non-printable character U+00A0 (1903960476.py, line 13)

In [42]:
######Comma notation to reach elements in a 2D Numpy array
print(array_2d[0,0]) #10
print(array_2d[0,1]) #15
print(array_2d[0,2]) #20

10
15
20


In [43]:
# Selects elements in the 2D array 'array_2d' from the first two rows (up to the 2nd row)
# and starting from the second column (column 1 onwards).
array_2d[:2,1:] 

array([[15, 20],
       [30, 35]])

In [44]:
print(array_2d[:2]) ##grab the first two rows

[[10 15 20]
 [25 30 35]]


In [45]:
arr = np.arange(1,21)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
bool_arr = arr < 15

In [48]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [49]:
arr[bool_arr] ##get the slice of the arr where bool_arr is true.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
print(arr[bool_arr]) ##get the slice of the arr where bool_arr is true.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [51]:
arr[arr > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
arr[arr <= 11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
arr_2d = np.arange(50).reshape(5,10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [54]:
print(arr_2d[1:3,3:5]) ##from row1 to row2 and from column3 to column4.

[[13 14]
 [23 24]]


In [55]:
####Numpy Operations
import numpy as np

my_arr = np.arange(0,11)

In [56]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
my_arr + my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
3 * my_arr - 9 * my_arr

array([  0,  -6, -12, -18, -24, -30, -36, -42, -48, -54, -60])

In [59]:
my_arr + 1000

array([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [60]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [61]:
my_arr / my_arr

/var/folders/8c/5wkl40l145338h0xwgv0k6vm0000gn/T/ipykernel_54305/2285140018.py:1: RuntimeWarning: invalid value encountered in true_divide
  my_arr / my_arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
1/0

ZeroDivisionError: division by zero

In [63]:
1/my_arr

/var/folders/8c/5wkl40l145338h0xwgv0k6vm0000gn/T/ipykernel_54305/1710470366.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/my_arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [64]:
print(my_arr**3)

[   0    1    8   27   64  125  216  343  512  729 1000]


In [65]:
print(my_arr**2)  # Squares each element in my_arr.

[  0   1   4   9  16  25  36  49  64  81 100]


In [66]:
np.sqrt(my_arr**3)

array([ 0.        ,  1.        ,  2.82842712,  5.19615242,  8.        ,
       11.18033989, 14.69693846, 18.52025918, 22.627417  , 27.        ,
       31.6227766 ])

In [67]:
np.sqrt(my_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [68]:
print(np.sqrt(my_arr**5)) ##usage of np.sqrt function to get the square root of each element in the array.

[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.
 316.22776602]


In [69]:
print(np.exp(my_arr)) ###calculates the exponential of each element in the array.

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


In [70]:
np.max(my_arr)

10

In [71]:
print(np.max(my_arr))

10


In [72]:
print(np.sin(my_arr))
print()
print(np.cos(my_arr))
print()
print(np.tan(my_arr))
print()
print(1/np.tan(my_arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566  0.64836083]

[        inf  0.64209262 -0.45765755 -7.01525255  0.86369115 -0.29581292
 -3.436353    1.14751542 -0.14706506 -2.21084541  1.54235105]


/var/folders/8c/5wkl40l145338h0xwgv0k6vm0000gn/T/ipykernel_54305/3245661216.py:7: RuntimeWarning: divide by zero encountered in true_divide
  print(1/np.tan(my_arr))


In [73]:
np.log(my_arr)

/var/folders/8c/5wkl40l145338h0xwgv0k6vm0000gn/T/ipykernel_54305/1063440636.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(my_arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [74]:
print(np.add(1,2))

3


In [75]:
result = np.subtract(np.max([5, 3]), np.min([77, 9]))
print(result)

-4


In [76]:
np.random.rand(25) #Generates 25 random numbers from a uniform distribution (numbers are between 0 and 1).

array([0.94736315, 0.1403436 , 0.53790664, 0.84897623, 0.83123784,
       0.70406724, 0.25712155, 0.40335835, 0.21066168, 0.36780657,
       0.53955007, 0.93322795, 0.64371641, 0.25904967, 0.88257587,
       0.6630547 , 0.6741547 , 0.15563047, 0.349906  , 0.37273134,
       0.66466043, 0.68359917, 0.28062739, 0.0340056 , 0.71724265])

In [77]:
np.random.randn(30)  #30 random numbers drawn from a standard normal distribution.

array([ 1.30842756, -1.35047093, -0.53111256,  1.30393627,  1.16763642,
        1.11860529, -0.72223246,  1.35366858,  0.26412857,  1.05718545,
       -1.25360146,  0.04042753, -1.23266154,  1.01414932, -0.3802703 ,
       -1.108127  , -1.00177831,  1.51866628, -0.3730583 , -0.39702563,
        0.15533587,  0.52252486, -0.06176189,  1.18849394, -0.719075  ,
       -0.56499317, -0.44687187,  0.17729297, -0.53434344,  0.48974449])

In [78]:
np.linspace(0,1,20) #creates 20 linearly spaced points between 0 and 1.

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [79]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [80]:
print(mat[2:5,1:])
print()
print(mat[2:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [82]:
##axis = 0 (columnwise summation)##
##axis = 1 (rowwise summation)##


sum_of_all = mat.sum()
print("Summation of all values in the matrix mat is:  "+str(sum_of_all)+"")

columnwise_summations = mat.sum(axis = 0)
print("Columnwise summations for the matrix mat are: "+str(columnwise_summations)+"")

rowwise_summations = mat.sum(axis = 1)
print("Rowwise summations for the matrix mat are: "+str(rowwise_summations)+"")

standard_dev = mat.std()
print("The standard deviation of the values in the matrix mat is: "+str(standard_dev)+"")

Summation of all values in the matrix mat is:  325
Columnwise summations for the matrix mat are: [55 60 65 70 75]
Rowwise summations for the matrix mat are: [ 15  40  65  90 115]
The standard deviation of the values in the matrix mat is: 7.211102550927978
